version: "3.8"

services:
  db:
    image: mysql:8
    container_name: erp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: erp_aero
      MYSQL_USER: erp_user
      MYSQL_PASSWORD: erp_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
